[versions]
agp = "8.13.2"
appcompat = "1.7.1"
avifIntegration = "5.0.5"
commonsText = "1.14.0"
glide = "5.0.5"
glideSvg = "4.0.2"
jsoup = "1.21.2"
lingua = "1.2.2"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
media3Exoplayer = "1.9.0"
recyclerview = "1.4.0"
rome = "2.0.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
avif-integration = { module = "com.github.bumptech.glide:avif-integration", version.ref = "avifIntegration" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-svg = { module = "com.github.qoqa:glide-svg", version.ref = "glideSvg" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
lingua = { module = "com.github.pemistahl:lingua", version.ref = "lingua" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "media3Exoplayer" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
rome = { module = "com.rometools:rome", version.ref = "rome" }
rome-modules = { module = "com.rometools:rome-modules", version.ref = "rome" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

